# Finding frequent itemsets and association rules

### Library: mlxtend
We are going to use the library mlxtend which contains an implementation of the apriori algorithm. Click on the following <a href="http://rasbt.github.io/mlxtend/user_guide/frequent_patterns/association_rules/">link</a>. We recommend to install it using

pip install mlxtend

or

conda install mlxtend

Sometimes using the previous commands the library is not correctly installed, especially in the case when there are multiple Python versions installed on your Jupyter notebook. In that case, we recommend to use the command shown in the next cell (directly in your Jupyter notebook):

In [1]:
import sys
!{sys.executable} -m pip install mlxtend

Requirement already satisfied: mlxtend in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (0.17.2)
Requirement already satisfied: scipy>=1.2.1 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from mlxtend) (1.4.1)
Requirement already satisfied: joblib>=0.13.2 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from mlxtend) (0.14.1)
Requirement already satisfied: setuptools in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from mlxtend) (46.0.0)
Requirement already satisfied: pandas>=0.24.2 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from mlxtend) (1.0.3)
Requirement already satisfied: scikit-learn>=0.20.3 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from mlxtend) (0.22.2.post1)
Requirement already satisfied: matplotlib>=3.0.0 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from mlxtend) (3.2.1)
Requirement already satisfied: numpy>=1.16.2 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from mlxtend) (1.18.2)
Requirement already satisfied: python-dateutil>=2.6.1 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from pandas>=0.24.2->mlxtend) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from pandas>=0.24.2->mlxtend) (2019.3)
Requirement already satisfied: cycler>=0.10 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from matplotlib>=3.0.0->mlxtend) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from matplotlib>=3.0.0->mlxtend) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from matplotlib>=3.0.0->mlxtend) (2.4.6)
Requirement already satisfied: six>=1.5 in /Users/maurosozio/py_37_env/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas>=0.24.2->mlxtend) (1.14.0)
WARNING: You are using pip version 20.0.2; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/maurosozio/py_37_env/bin/python3 -m pip install --upgrade pip' command.

### One-hot encoding

Sometimes it is required to transform categorical data where features might take more than two values into one-hot encoding, where each feature can take either 0 or 1 (or True/False). For example, let's consider the following set of baskets with each basket containing all the items bought during a simple trip to the supermarket. Using the following script (which uses a TransactionEncoder from mlxtend) we obtain a one-hot encoding of the data, which is required by the apriori method of mlxtend:

In [10]:
from mlxtend.preprocessing import TransactionEncoder

dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
te_ary

array([[False, False, False,  True, False,  True,  True,  True,  True,
        False,  True],
       [False, False,  True,  True, False,  True, False,  True,  True,
        False,  True],
       [ True, False, False,  True, False,  True,  True, False, False,
        False, False],
       [False,  True, False, False, False,  True,  True, False, False,
         True,  True],
       [False,  True, False,  True,  True,  True, False, False,  True,
        False, False]])

Observe that we have now a number of features being equal to the number of items in the data. Each column corresponds to a feature, while each row-column entry specifies whether the corresponding basket contains the corresponding feature or not (e.g. "Milk").

### Frequent itemsets and association rules

Finally we are able to run apriori on the data represented with one-hot encoding using the corresponding methods from mlxtend. Please find below the full code:

In [8]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori


dataset = [['Milk', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Dill', 'Onion', 'Nutmeg', 'Kidney Beans', 'Eggs', 'Yogurt'],
           ['Milk', 'Apple', 'Kidney Beans', 'Eggs'],
           ['Milk', 'Unicorn', 'Corn', 'Kidney Beans', 'Yogurt'],
           ['Corn', 'Onion', 'Onion', 'Kidney Beans', 'Ice cream', 'Eggs']]

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)

frequent_itemsets

from mlxtend.frequent_patterns import association_rules

a=association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

a[["antecedents","consequents","support","confidence"]]

              antecedents            consequents  support  confidence
0          (Kidney Beans)                 (Eggs)      0.8        0.80
1                  (Eggs)         (Kidney Beans)      0.8        1.00
2                  (Eggs)                (Onion)      0.6        0.75
3                 (Onion)                 (Eggs)      0.6        1.00
4                  (Milk)         (Kidney Beans)      0.6        1.00
5                 (Onion)         (Kidney Beans)      0.6        1.00
6                (Yogurt)         (Kidney Beans)      0.6        1.00
7           (Onion, Eggs)         (Kidney Beans)      0.6        1.00
8    (Kidney Beans, Eggs)                (Onion)      0.6        0.75
9   (Kidney Beans, Onion)                 (Eggs)      0.6        1.00
10                 (Eggs)  (Kidney Beans, Onion)      0.6        0.75
11                (Onion)   (Kidney Beans, Eggs)      0.6        1.00

### DataFrame

One convenient way to load data from an input file and perform some preprocessing on it is to use panda DataFrame. A DataFrame is a "two-dimensional, size-mutable, potentially heterogeneous tabular data." It contains several tools to process and handle tabular data. Click on this <a href="https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html">link</a> for a documentation. 

To use a DataFrame we need to install the "pandas" library with any of the methods we saw up to now.

In [9]:
import pandas as pd

#read order_data.csv and create a DataFrame with that content
data = pd.read_csv(r"order_data.csv",delimiter=" ",header=None)
data

,0,1,2,3,4,5,6,7,8
0,toothpaste,brush,milk,cereals,honey,bread,butter,cheese,yogurt
1,milk,cereals,honey,bread,cheese,razor,gel,shampoo,NaN
2,milk,cereals,honey,cheese,soap,shampoo,NaN,NaN,NaN
3,honey,bread,butter,cheese,mouthwash,toothpaste,NaN,NaN,NaN
4,cereals,honey,bread,butter,gel,soap,NaN,NaN,NaN
5,cheesse,yogurt,milk,cereals,honey,shampoo,gel,NaN,NaN
6,honey,bread,cheese,razor,butter,yogurt,NaN,NaN,NaN
7,honey,bread,cheese,butter,milk,NaN,NaN,NaN,NaN
8,cereals,butter,cookies,chips,NaN,NaN,NaN,NaN,NaN
9,cerals,cheese,yogurt,cookies,chips,NaN,NaN,NaN,NaN
10,toothpaste,brush,gel,shampoo,soap,cookies,chips,NaN,NaN
11,toothpaste,brush,gel,razor,mouthwash,milk,cookies,NaN,NaN
12,razor,shampoo,gel,soap,bread,butter,NaN,NaN,NaN
13,brush,shampoo,gel,toothpaste,mouthwash,bread,cheese,NaN,NaN
14,mouthwash,toothpaste,soap,shampoo,cheese,yogurt,NaN,NaN,NaN
15,razor,mouthwash,soap,butter,bread,cheese,NaN,NaN,NaN
16,shampoo,soap,gel,milk,honey,cereals,NaN,NaN,NaN
17,toothpaste,razor,gel,brush,mouthwash,shampoo,NaN,NaN,NaN
18,gel,razor,shampoo,milk,cereals,bread,cookies,NaN,NaN
19,mouthwash,toothpaste,milk,bread,cookies,NaN,NaN,NaN,NaN

In [1]:
#we run apriori on the order_data.csv file

import math
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules


data = pd.read_csv(r"order_data.csv",delimiter=" ",header=None)

#preprocessing: change to one hot encoding so as to be able to use apriori from mlxtend
d=data.values.tolist()

#removing nan values
for i in range(len(d)):
    j=0
    while(True):
        if (type(d[i][j])==float and math.isnan(d[i][j])) :
            del d[i][j]
            j-=1
        j+=1
        if (j>len(d[i])-1):
            break

te = TransactionEncoder()
te_ary = te.fit(d).transform(d)
df = pd.DataFrame(te_ary, columns=te.columns_)

#computing frequent itemsets and association rules
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

a=association_rules(frequent_itemsets, metric="confidence", min_threshold=0.6)

#visualizing association rules results
a[["antecedents","consequents","support","confidence"]]

            antecedents         consequents  support  confidence
0               (bread)            (butter)     0.35    0.636364
1              (butter)             (bread)     0.35    0.875000
2               (bread)            (cheese)     0.35    0.636364
3              (cheese)             (bread)     0.35    0.700000
4               (honey)             (bread)     0.30    0.666667
..                  ...                 ...      ...         ...
99   (shampoo, cereals)       (honey, milk)     0.20    0.800000
100     (shampoo, milk)    (honey, cereals)     0.20    0.800000
101    (honey, cereals)     (shampoo, milk)     0.20    0.666667
102       (honey, milk)  (shampoo, cereals)     0.20    0.666667
103     (cereals, milk)    (honey, shampoo)     0.20    0.666667

[104 rows x 4 columns]

In [3]:
type(a["antecedents"][99]) #prints frozenset

frozenset

In [13]:
#frozenset is very similar to a set in Python with the main difference that cannot be changed.
#so we can check if a rule contains shampoo and honey as follows
i=99
if ("shampoo" in a["antecedents"][i] and "honey" in a["consequents"][i] ):
    print ("The "+str(i)+" rule talks about shampoo and honey:" )
else:
    print ("The "+str(i)+"th rule does not talk about shampoo and honey:" )

The 99 rule talks about shampoo and honey:

In [1]:
import math
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules


data = pd.read_csv(r"mammographic_masses.csv",delimiter=",",header=0)

#preprocessing: change to one hot encoding so as to be able to use apriori from mlxtend
d=data.values.tolist()

#removing nan values
for i in range(0,len(d)):
    j=0
    while(True):
        if (type(d[i][j])==float and math.isnan(d[i][j])) :
            del d[i][j]
            j-=1
        j+=1
        if (j>len(d[i])-1):
            break

#adding attributes
for i in range(len(d)):
    for j in range (len(d[i])):
        d[i][j]=data.columns[j] + "=" +str(d[i][j])

            
te = TransactionEncoder()
te_ary = te.fit(d).transform(d)

df = pd.DataFrame(te_ary, columns=te.columns_)

#this part needs to be filled...